services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123321
      - MYSQL_DATABASE=app
    ports:
      - 3306:3306
    volumes:
      - /tmp/data/:/var/lib/mysql

  app:
    build: .
    depends_on:
      - mysqldb
    links: 
      - mysqldb
    ports:
      - 3000:3000