FROM nginx:1.27.1
# RUN apt-get update && apt-get install -y git

# Clone the repo and copy the nginx.conf file
# RUN git clone https://github.com/etec-integration-project/etec-pi-2024-backend-A-Simoncito.git /tmp/repo

# COPY /tmp/repo/nginx.conf /etc/nginx/nginx.conf

ADD https://raw.githubusercontent.com/etec-integration-project/etec-pi-2024-backend-A-Simoncito/main/nginx.conf /etc/nginx/nginx.conf